set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_HS
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_VS
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg0[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg0[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg0[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg0[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg0[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg0[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg0[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg0[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to clk_50
set_instance_assignment -name IO_STANDARD "3.3 V Schmitt Trigger" -to rst_n
set_instance_assignment -name IO_STANDARD "3.3 V Schmitt Trigger" -to up
set_location_assignment PIN_AA1 -to VGA_R[3]
set_location_assignment PIN_V1 -to VGA_R[2]
set_location_assignment PIN_Y2 -to VGA_R[1]
set_location_assignment PIN_Y1 -to VGA_R[0]
set_location_assignment PIN_W1 -to VGA_G[3]
set_location_assignment PIN_T2 -to VGA_G[2]
set_location_assignment PIN_R2 -to VGA_G[1]
set_location_assignment PIN_R1 -to VGA_G[0]
set_location_assignment PIN_P1 -to VGA_B[3]
set_location_assignment PIN_T1 -to VGA_B[2]
set_location_assignment PIN_P4 -to VGA_B[1]
set_location_assignment PIN_N2 -to VGA_B[0]
set_location_assignment PIN_N3 -to VGA_HS
set_location_assignment PIN_N1 -to VGA_VS
set_location_assignment PIN_P11 -to clk_50
set_location_assignment PIN_B8 -to rst_n
set_location_assignment PIN_A7 -to up
set_location_assignment PIN_D15 -to seg0[7]
set_location_assignment PIN_C17 -to seg0[6]
set_location_assignment PIN_D17 -to seg0[5]
set_location_assignment PIN_E16 -to seg0[4]
set_location_assignment PIN_C16 -to seg0[3]
set_location_assignment PIN_C15 -to seg0[2]
set_location_assignment PIN_E15 -to seg0[1]
set_location_assignment PIN_C14 -to seg0[0]
set_location_assignment PIN_C18 -to seg1[0]
set_location_assignment PIN_D18 -to seg1[1]
set_location_assignment PIN_E18 -to seg1[2]
set_location_assignment PIN_B16 -to seg1[3]
set_location_assignment PIN_A17 -to seg1[4]
set_location_assignment PIN_A18 -to seg1[5]
set_location_assignment PIN_B17 -to seg1[6]
set_location_assignment PIN_A16 -to seg1[7]
set_location_assignment PIN_B20 -to seg2[0]
set_location_assignment PIN_A20 -to seg2[1]
set_location_assignment PIN_B19 -to seg2[2]
set_location_assignment PIN_A21 -to seg2[3]
set_location_assignment PIN_B21 -to seg2[4]
set_location_assignment PIN_C22 -to seg2[5]
set_location_assignment PIN_B22 -to seg2[6]
set_location_assignment PIN_A19 -to seg2[7]
